version: '3'

volumes:
  node_modules:
services:
  seamath-frontend-dev:
    container_name: seamath-frontend-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
      - '24678:24678'
    volumes:
      - .:/src
      - node_modules:/src/node_modules
